"use client";

import { useState, useCallback } from "react";
import { Sparkles, Loader2, ChevronDown, ChevronUp } from "lucide-react";

interface ArticleSummaryProps {
  content: string;
}

export default function ArticleSummary({ content }: ArticleSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(false);

  const generateSummary = useCallback(async () => {
    if (summary) {
      setExpanded((prev) => !prev);
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const res = await fetch("/api/ai/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });

      const data = await res.json();

      if (data.success && data.summary) {
        setSummary(data.summary);
        setExpanded(true);
      } else {
        setError(data.error || "Failed to generate summary");
      }
    } catch {
      setError("Could not generate summary. Please try again.");
    } finally {
      setLoading(false);
    }
  }, [content, summary]);

  return (
    <div className="bg-zinc-900/80 border border-zinc-800 rounded-xl overflow-hidden">
      <button
        onClick={generateSummary}
        disabled={loading}
        className="w-full flex items-center justify-between p-4 text-left hover:bg-zinc-800/50 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="p-2 bg-brand/10 rounded-lg">
            <Sparkles size={16} className="text-brand" />
          </div>
          <div>
            <span className="text-sm font-semibold text-white">AI Summary</span>
            <p className="text-[11px] text-gray-500">
              {summary ? "Click to toggle summary" : "Get a quick overview of this article"}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {loading ? (
            <Loader2 size={16} className="text-brand animate-spin" />
          ) : summary ? (
            expanded ? (
              <ChevronUp size={16} className="text-gray-400" />
            ) : (
              <ChevronDown size={16} className="text-gray-400" />
            )
          ) : (
            <Sparkles size={14} className="text-brand" />
          )}
        </div>
      </button>

      {expanded && summary && (
        <div className="px-4 pb-4 border-t border-zinc-800">
          <div className="mt-3 text-sm text-gray-300 leading-relaxed whitespace-pre-line">
            {summary}
          </div>
          <div className="mt-3 flex items-center gap-1 text-[10px] text-gray-600">
            <Sparkles size={10} />
            Generated by AI · may contain inaccuracies
          </div>
        </div>
      )}

      {error && (
        <div className="px-4 pb-4 border-t border-zinc-800">
          <p className="mt-3 text-sm text-red-400">{error}</p>
        </div>
      )}
    </div>
  );
}
