"use client";

import { useState } from "react";
import {
  FileText,
  Edit,
  Trash2,
  Clock,
  Eye,
  Send,
  Search,
} from "lucide-react";

interface Draft {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  wordCount: number;
  readingTime: number;
  createdAt: string;
  updatedAt: string;
  aiConfidence: number;
  status: "draft" | "review" | "ready";
}

export default function AIDraftsPage() {
  const [drafts, setDrafts] = useState<Draft[]>([
    {
      id: "1",
      title: "New Infrastructure Project Launches in Kampala",
      excerpt: "The government has officially launched a major infrastructure project...",
      category: "Politics",
      wordCount: 1200,
      readingTime: 5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      aiConfidence: 0.87,
      status: "draft",
    },
    {
      id: "2",
      title: "Tech Startups Raise Record Funding in East Africa",
      excerpt: "East African startups have raised over $500 million in the first half of 2026...",
      category: "Technology",
      wordCount: 850,
      readingTime: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      aiConfidence: 0.92,
      status: "review",
    },
  ]);

  const [searchQuery, setSearchQuery] = useState("");

  const handleDelete = (id: string) => {
    setDrafts(drafts.filter((d) => d.id !== id));
  };

  const handlePublish = (id: string) => {
    setDrafts(
      drafts.map((d) => (d.id === id ? { ...d, status: "ready" as const } : d))
    );
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "ready":
        return "bg-green-100 text-green-800";
      case "review":
        return "bg-yellow-100 text-yellow-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <FileText size={24} className="text-blue-500" />
            AI Drafts
          </h1>
          <p className="text-sm text-gray-500">Articles generated by AI agents</p>
        </div>
      </div>

      <div className="relative">
        <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
        <input
          type="text"
          placeholder="Search drafts..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full pl-10 pr-4 py-2 border rounded-lg"
        />
      </div>

      <div className="space-y-4">
        {drafts.map((draft) => (
          <div key={draft.id} className="bg-zinc-900 border-zinc-800 rounded-lg p-4">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <h3 className="font-semibold text-lg">{draft.title}</h3>
                  <span
                    className={`px-2 py-0.5 rounded text-xs font-medium ${getStatusBadge(
                      draft.status
                    )}`}
                  >
                    {draft.status}
                  </span>
                </div>
                <p className="text-sm text-gray-600 mb-3">{draft.excerpt}</p>
                <div className="flex items-center gap-4 text-xs text-gray-500">
                  <span>{draft.category}</span>
                  <span>{draft.wordCount} words</span>
                  <span>{draft.readingTime} min read</span>
                  <span>AI Confidence: {Math.round(draft.aiConfidence * 100)}%</span>
                  <span className="flex items-center gap-1">
                    <Clock size={12} />
                    {new Date(draft.updatedAt).toLocaleTimeString()}
                  </span>
                </div>
              </div>
              <div className="flex gap-2">
                <button className="p-2 text-gray-400 hover:text-blue-500">
                  <Eye size={16} />
                </button>
                <button className="p-2 text-gray-400 hover:text-green-500">
                  <Edit size={16} />
                </button>
                <button
                  onClick={() => handlePublish(draft.id)}
                  className="p-2 text-gray-400 hover:text-brand"
                >
                  <Send size={16} />
                </button>
                <button
                  onClick={() => handleDelete(draft.id)}
                  className="p-2 text-gray-400 hover:text-red-500"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
